---
title: "Tweet level morality, stance, sentiment - logistic random coefficient model"
author: "Meltem Ozcan"
date: "2023-12-09"
output: pdf_document
---

```{r warning = FALSE, message=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(glmmTMB)
library(dplyr)
library(tidyr)
library(lme4)
```

```{r warning = FALSE, message = FALSE}
dat <- readr::read_csv("Data/final_wave2_upd.csv")
dat$dayofweek <- as.factor(dat$dayofweek)
levels(dat$dayofweek) <- c("M", "Tue", "W", "Thu", "F", "Sat", "Sun")
```


```{r}
dat$life <- factor(dat$life, ordered = FALSE)
dat$care <- factor(dat$care, ordered = FALSE)
dat$fairness <- factor(dat$fairness, ordered = FALSE)
dat$authority <- factor(dat$authority, ordered = FALSE)
dat$loyalty <- factor(dat$loyalty, ordered = FALSE)
dat$purity <- factor(dat$purity, ordered = FALSE)
dat$binary_morality <- factor(dat$binary_morality, ordered = FALSE)
dat$sentiment <- factor(dat$sentiment, ordered = FALSE)
# dat$sentiment = ordered(as.factor(dat$sentiment), 
#                         c("negative", "neutral", "positive"))
# dat$prolife_prochoice <- ordered(as.factor(dat$prolife_prochoice),
#                                  c("life", "neutral", "choice"))
# dat$binary_morality <- ordered(as.factor(dat$binary_morality),
#                                ordered(c("moral", "non-moral")))
# dat$care <- ordered(as.factor(dat$care),
#                                ordered(c("0", "1")))
# dat$fairness <- ordered(as.factor(dat$fairness),
#                                ordered(c("0", "1")))
# dat$authority <- ordered(as.factor(dat$authority),
#                                ordered(c("0", "1")))
# dat$loyalty <- ordered(as.factor(dat$loyalty),
#                                ordered(c("0", "1")))
# dat$purity <- ordered(as.factor(dat$purity),
#                                ordered(c("0", "1")))
dat$windows <- ""
dat[dat$pre52_Dobbs==1, "windows"] <- "pre-Dobbs"
dat[dat$post52_Overturn==1, "windows"]<- "post-overturn"
dat$windows <- ordered(as.factor(dat$windows), 
                       c("pre-Dobbs", "post-Dobbs & pre-overturn", "post-overturn"))
```


# Can individuals’ moral framing of the tweet predict whether they are pro-life or pro-choice? 

## Pro-Life
```{r}
M2_life_binaryM_m1 <- glmer(life ~ binary_morality + dayofweek + 
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M2_life_binaryM_m1)
```

```{r}
# M2_life_mft5_m2 <- glmer(life ~ care + fairness + authority + loyalty + purity +
#                               dayofweek + 
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# M2_life_mft5_m2
# summary(M2_life_mft5_m2)


M2_life_mft5_m2_unord <- glmer(life ~ care + fairness + authority + loyalty + 
                                 purity + 
                              dayofweek + 
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M2_life_mft5_m2_unord)
```


```{r}
M2_life_mft5_m3 <- glmer(life ~ care + fairness + authority + loyalty + purity + 
                              dayofweek +
                              positive +
                              negative +
                              neutral +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))

summary(M2_life_mft5_m3)
```


```{r}

M2_life_mft5_m4 <- glmer(life ~ binary_morality * sentiment +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))

summary(M2_life_mft5_m4)
```


## Neutral

```{r}
# M2_ab_neutral_binaryM_m1 <- glmer(ab_neutral ~ binary_morality + dayofweek + 
#                               (1 | author.id),
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# summary(M2_ab_neutral_binaryM_m1)
```

```{r}
# M2_ab_neutral_mft5_m2 <- glmer(ab_neutral ~ care + fairness + authority + loyalty + 
#                                  purity + 
#                               dayofweek + 
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# 
# summary(M2_ab_neutral_mft5_m2)
```

```{r}
# M2_ab_neutral_mft5_m3 <- glmer(ab_neutral ~ care + fairness + authority + loyalty + 
#                                  purity + 
#                                 dayofweek +
#                                 positive +
#                                 negative +
#                                 neutral +
#                                 (1 | author.id), 
#                               data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# summary(M2_ab_neutral_mft5_m3)
```

```{r}
# 
# M2_ab_neutral_mft5_m4 <- glmer(ab_neutral ~ binary_morality * sentiment +
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# 
# summary(M2_ab_neutral_mft5_m4)
```


## Pro-Choice

```{r}
M2_choice_binaryM_m1 <- glmer(choice ~ binary_morality + dayofweek + 
                              (1 | author.id),
                            data = dat, family = binomial(link = "logit"),
                          glmerControl(optimizer = "bobyqa"))
summary(M2_choice_binaryM_m1)
```

```{r}
M2_choice_mft5_m2 <- glmer(ab_neutral ~ care + fairness + authority + loyalty + 
                                 purity +
                              dayofweek + 
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                          glmerControl(optimizer = "bobyqa"))

summary(M2_choice_mft5_m2)
```

```{r}
M2_choice_mft5_m3 <- glmer(choice ~ care + fairness + authority + loyalty + 
                             purity + 
                              dayofweek +
                              positive +
                              negative +
                              neutral +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M2_choice_mft5_m3)
```

```{r}
M2_choice_mft5_m4 <- glmer(choice ~ binary_morality * sentiment + 
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M2_choice_mft5_m4)
```


```{r}
M2_choice_mft5_m4 <- glmer(choice ~ binary_morality * sentiment + 
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M2_choice_mft5_m4)
```



```{r}
M3_life_m1 <- glmer(life ~ care * positive + care * negative +
                      fairness * positive + fairness * negative +
                      authority * positive + authority * negative +
                      loyalty * positive + loyalty * negative +
                      purity * positive + purity * negative +
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M3_life_m1)
```

```{r}
M3_choice_m1 <- glmer(choice ~ care * positive + care * negative +
                      fairness * positive + fairness * negative +
                      authority * positive + authority * negative +
                      loyalty * positive + loyalty * negative +
                      purity * positive + purity * negative +
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M3_choice_m1)
```
```{r}
M4_choice_m1 <- glmer(choice ~ binary_morality * sentiment +ST_clin_total +
                        ST_MAB_md_cost22 +  ST_clin_prov_AB22 + 
                        ST_clin_prov_PAB22 + ST_clin_prov_MAB22 + 
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M4_choice_m1)
```


```{r}
M4_life_m1 <- glmer(life ~ binary_morality * sentiment +ST_clin_total +
                        ST_MAB_md_cost22 +  ST_clin_prov_AB22 + 
                        ST_clin_prov_PAB22 + ST_clin_prov_MAB22 + 
                              dayofweek +
                              (1 | author.id), 
                            data = dat, family = binomial(link = "logit"),
                         glmerControl(optimizer = "bobyqa"))
summary(M4_life_m1)
```

```{r}
# M2_life_mft5_m4 <- glmer(life ~ care + fairness + authority + loyalty + 
#                               dayofweek +
#                               positive +
#                               negative +
#                               neutral +
#                               region +
#                               ST_clin_total +
#                               ST_clin_prov_AB22+ 
#                               log(medincome) +
#                               FM_ratio +
#                               hisp_nonhisp_ratio +
#                               white_nonwhite_ratio +
#                               edu_ov25HS_GED +
#                               edu_F_overBA +
#                               edu_M_overBA +
#                               StrongRep2018_01 +
#                               StrongDem2018_01 +
#                               CompetitiveDemRep2018_01 +
#                               veryReligious2017 +
#                               TrumpPerc2020 +
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# 
# summary(M2_life_mft5_m4)
```

```{r}
# M2_ab_neutral_mft5_m4 <- glmer(ab_neutral ~ care + fairness + authority + loyalty + 
#                               dayofweek +
#                               positive +
#                               negative +
#                               neutral +
#                               region +
#                               ST_clin_total +
#                               ST_clin_prov_AB22+ 
#                               log(medincome) +
#                               FM_ratio +
#                               hisp_nonhisp_ratio +
#                               white_nonwhite_ratio +
#                               edu_ov25HS_GED +
#                               edu_F_overBA +
#                               edu_M_overBA +
#                               StrongRep2018_01 +
#                               StrongDem2018_01 +
#                               CompetitiveDemRep2018_01 +
#                               veryReligious2017 +
#                               TrumpPerc2020 +
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# 
# summary(M2_ab_neutral_mft5_m4)
```


```{r}
# M2_choice_mft5_m4 <- glmer(choice ~ care + fairness + authority + loyalty + 
#                               dayofweek +
#                               positive +
#                               negative +
#                               neutral +
#                               region +
#                               ST_clin_total +
#                               ST_clin_prov_AB22+ 
#                               log(medincome) +
#                               FM_ratio +
#                               hisp_nonhisp_ratio +
#                               white_nonwhite_ratio +
#                               edu_ov25HS_GED +
#                               edu_F_overBA +
#                               edu_M_overBA +
#                               StrongRep2018_01 +
#                               StrongDem2018_01 +
#                               CompetitiveDemRep2018_01 +
#                               veryReligious2017 +
#                               TrumpPerc2020 +
#                               (1 | author.id), 
#                             data = dat, family = binomial(link = "logit"),
#                          glmerControl(optimizer = "bobyqa"))
# 
# summary(M2_choice_mft5_m4)
```



