---
title: "Roe v Wade Overturn Data Visualizations"
author: "Meltem Ozcan"
date: "2023-11-24"
output: pdf_document
---
```{r}
# To read Twitter data and combine with state level info:
# source('processTwitterData.R')
# dt <- processTwitterData('<the name of the file/path>.csv')
# read in the compiled external data csv file -- see ExternalDataPreparation.R
# statelevel  <- read.csv('external/StateLevelExternalData2021.csv')
# dt <- left_join(dt, statelevel, by = join_by(state))
```

```{r warning = FALSE, message=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)
library(glmmTMB)  # for multilevel logistic models
library(sjPlot)
library(MuMIn)  # for R^2
```

```{r}
source('processTwitterData.R')
source('rm_dupl_empty_noneng.R')
source('clean_tweet.R')
before <- processTwitterData('twitterData/before_roe_sentiment.csv')
before$RoeWadeOverturn <- "before"
after <- processTwitterData('twitterData/after_roe_sentiment.csv')
after$RoeWadeOverturn <- "after"

# read in the compiled external data csv file -- see ExternalDataPreparation.R
statelev  <- read.csv('external/StateLevelExternalData2021.csv')
before <- left_join(before, statelev, by = join_by(state)) # 38599 x 92
after <- left_join(after, statelev, by = join_by(state))

dat22 <- rbind(before, after) 
dat22$RoeWadeOverturn <- factor(dat22$RoeWadeOverturn, levels = c("before", "after"))
dat22 <- dat22 %>% 
  mutate(preDobbsLeak = ifelse(tweeted_at < as.Date("2022-05-3"), 1, 0)) %>%
  select(-c(X, temp, STATE))

dat22 <- dat22 %>% 
  mutate(createdAccAfterLeak = 
           ifelse(as.Date(TwitterAccountCreatedAt) > as.Date("2022-05-3"), 1, 0),
         createdAccAfterOverturn = 
           ifelse(as.Date(TwitterAccountCreatedAt) > as.Date("2022-06-24"), 1, 0),
         accountMadeOn = date(TwitterAccountCreatedAt)
  )
```

```{r}
# REMOVE DUPLICATES/EMPTY TWEETS
dat22$record_id <- seq_len(dim(dat22)[1])
dat <- dat22
dat <- rm_dupl_empty_noneng(dat)
# removed 3846 records where the tweet was empty or only contained account 
# handle(s)
# if i keep dataset <- dataset %>% ...%>% filter(row_number() == 1) in 
# rm_dupl_empty_noneng.R 33099 rows deleted-- for now, comment it out, if there 
# is time come back and investigate further if it correctly removes the records
# within a given author.id for which cleantext is duplicated and keeps only one
# instance of the duplicated cleantext per author, while retaining it if it's 
# used by other authors

# investigating which records were deleted:
dat22$cleantext <- clean_tweet(dat22$vader_preprocessed_text)
removed_rec <- dat22[dat22$record_id %in% (seq_len(dim(dat22)[1])[!seq_len(dim(dat22)[1])%in%dat$record_id]),]

total_num_tweets_per_auth <- dat %>% 
    group_by(author.id) %>% 
    summarise(num_tweets_by_author = n_distinct(record_id)) %>% 
    arrange(desc(num_tweets_by_author)) 
# after examining tweets, 1113146496592044032 has 928 identical tweets about
# a start up, with different accounts tagged. remove:
dat <- dat[dat$author.id!="1113146496592044032",]
```

-- note: last updated the above data processing code on Nov 24, 2pm--




```{r}
# 174 days Jan 1-Jun 24 2022, n = 38599
beforeTweetsPerDay <- before %>% dplyr::count(tweetCountOnDay = date_of_tweet) 
# 190 days Jun 24 2022 - Dec 31 2022;  217739 tweets
afterTweetsPerDay <- after %>% dplyr::count(tweetCountOnDay = date_of_tweet) 
# 370 days
TweetsPerDay <- dat %>% dplyr::count(tweetCountOnDay = date_of_tweet) 
```

```{r echo = FALSE}
ggplot(beforeTweetsPerDay, aes(x = tweetCountOnDay, y = n)) + 
  geom_line() + 
  geom_vline(xintercept = as.Date("2022-05-02"), color = "blue", lty = "dashed") + 
  ggtitle("Number of tweets per day between January 1, 2022 and January 6, 2023") +
  ylab("Number of tweets") +
  xlab("Time")+
  scale_x_date(breaks = as.Date(c("2022-01-01","2022-02-01", "2022-03-01",
                                  "2022-04-01", "2022-05-01","2022-06-01")), 
               labels = c("Jan", "Feb", "March", "Apr", "May", "June")) +
  theme_bw()
# May 2 2022: Politico published a leaked draft of the Supreme 
# Court majority decision to overturn Roe v. Wade 
# May 12-14: major protests and rallies
```
```{r echo = FALSE}
ggplot(afterTweetsPerDay, aes(x = tweetCountOnDay, y = n)) + 
  geom_line() + 
  ggtitle("Number of tweets per day between June 24, 2022 and January 6, 2022") +
  ylab("Number of tweets") +
  xlab("Time")+
  scale_x_date(breaks = as.Date(c("2022-06-01","2022-07-01", "2022-08-01",
                                  "2022-09-01", "2022-10-01","2022-11-01",
                                  "2022-12-01", "2023-01-01")), 
               labels = c("June", "July", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan")) +
  theme_bw()
```

```{r echo = FALSE}
ggplot(TweetsPerDay, aes(x = tweetCountOnDay, y = n)) + 
  geom_line() + 
  geom_vline(xintercept = as.Date("2022-05-02"), color = "blue", lty = "dashed") + 
   geom_vline(xintercept = as.Date("2022-06-24"), color = "red", lty = "dashed") + 
  ggtitle("Number of tweets per day between January 1, 2022 and January 6, 2023") +
  ylab("Number of tweets") +
  xlab("Time")+
  scale_x_date(breaks = as.Date(c("2022-01-01","2022-02-01", "2022-03-01",
                                  "2022-04-01", "2022-05-01","2022-06-01",
                                  "2022-07-01", "2022-08-01", "2022-09-01",
                                  "2022-10-01","2022-11-01", "2022-12-01",
                                  "2023-01-01")), 
               labels = c("Jan 2022", "Feb", "March", "Apr", "May", "June", 
                          "July", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan 2023")) +
  theme_bw()
```


```{r}
# authors/accounts per day
newAccsPerDay <- dat %>% 
  filter(accountMadeOn > as.Date("2021-12-31")) %>% 
  count(newAccCount = accountMadeOn) 

ggplot(newAccsPerDay, aes(x = newAccCount, y = n)) + 
  geom_line() + theme_bw()+
  ggtitle("Number of new accounts per day between January 1, 2022 and January 6, 2023") +
  ylab("Number of new accounts") +
  xlab("Time")
# These peaks are related to Elon Musk acquiring Twitter, agreement reached 4/26
```

```{r message = FALSE}
# before & after sentiment comparison


#sum(dat$vader_compound==0)#48727 instances have sentiment=0
table(dat$sentiment)
round(prop.table(table(dat$sentiment)),3)
bef_af_rvw_s <- dat %>% 
  group_by(RoeWadeOverturn, sentiment) %>%
  summarise(n=n()) %>% mutate(prop=n/sum(n))

bef_af_rvw_s <- as.data.frame(bef_af_rvw_s)
bef_af_rvw_s$RoeWadeOverturn <- as.factor(bef_af_rvw_s$RoeWadeOverturn)
levels(bef_af_rvw_s$RoeWadeOverturn) <- c('Before Overturn','After Overturn')
#library(RColorBrewer)

ggplot(bef_af_rvw_s, aes(sentiment, prop, fill = sentiment)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("#91bfdb", "#DEDEDE",  "#ef8a62")) +
  labs(fill = "sentiment")+
  ylab("Proportion of tweets")+
facet_wrap(~RoeWadeOverturn) + theme_bw()+geom_text(aes(label=round(prop,3)), position=position_dodge(width=0.9), vjust=-0.25)

sent_counts <- data.frame(cbind(bef_af_rvw_s[1:3, "n"], bef_af_rvw_s[4:6, "n"]))
rownames(sent_counts) <- c("negative", "neutral", "positive")
colnames(sent_counts) <- levels(bef_af_rvw_s$RoeWadeOverturn)
```




```{r}
# compute proportions of sentiment labels per state before/ after the
#overturn and in general
state_sent_props <- dat %>% 
  group_by(state, sentiment) %>%
  summarise(n=n()) %>% mutate(prop=n/sum(n))
state_sent_props_bef <- dat %>% 
  filter(RoeWadeOverturn == "before") %>%
  group_by(state, sentiment) %>%
  summarise(n=n()) %>% mutate(prop=n/sum(n))
state_sent_props_af <- dat %>% 
  filter(RoeWadeOverturn == "after") %>%
  group_by(state, sentiment) %>%
  summarise(n=n()) %>% mutate(prop=n/sum(n))

# create lists for the regions
us_regions <- read.csv("external/us_census_bureau_regions_and_divisions.csv")
us_regions <- us_regions %>% rename(state = State.Code, region = Region, 
                                    division = Division)
midwest <- us_regions[us_regions$region=="Midwest", "state"]
northeast <- us_regions[us_regions$region=="Northeast", "state"]
south <- us_regions[us_regions$region=="South", "state"]
west <- us_regions[us_regions$region=="West", "state"]
```

```{r}

barplot_state_sentiment_by_region <- function(propdf,
                                              listofstates, region, timeline) {
ggplot(propdf[propdf$state %in% listofstates,], 
       aes(sentiment, prop, fill = sentiment)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("#91bfdb", "#DEDEDE",  "#ef8a62")) +
  labs(fill = "sentiment")+
  ylab("Proportion of tweets")+
facet_wrap(~state) + 
  theme_bw() + theme(axis.text.x = element_blank())+
  geom_text(aes(label = round(prop,3)), 
            position = position_dodge(width=0.9), vjust=1.25, size = 3) + 
  scale_y_continuous(limits = c(0,1)) +
  ggtitle(paste0("Sentiment distribution of tweets in ", region,
                 " states ", timeline))+ theme(plot.title = element_text(size=11))

}

time_comp <- "(Jan 1 2022 - Jan 6 2023)"
time_bf <- "(Jan 1 2022 - June 24 2022)" 
time_af <-"(June 24 2022 - Jan 6 2023)"
```
## Northeastern states
```{r}

barplot_state_sentiment_by_region(state_sent_props, 
                                  northeast, 
                                  "northeastern", 
                                  time_bf)

barplot_state_sentiment_by_region(state_sent_props, 
                                  northeast, 
                                  "northeastern", 
                                  time_af)
```

## Midwestern states
```{r}

barplot_state_sentiment_by_region(state_sent_props, 
                                  midwest, 
                                  "midwestern", 
                                  time_bf)

barplot_state_sentiment_by_region(state_sent_props, 
                                  midwest, 
                                  "midwestern", 
                                  time_af)
```
## Southern states
```{r }

barplot_state_sentiment_by_region(state_sent_props, 
                                  south, 
                                  "southern", 
                                  time_bf)

barplot_state_sentiment_by_region(state_sent_props, 
                                  south, 
                                  "southern", 
                                  time_af)
```


## Western states
```{r }
barplot_state_sentiment_by_region(state_sent_props, 
                                  west, 
                                  "western", 
                                  time_bf)

barplot_state_sentiment_by_region(state_sent_props, 
                                  west, 
                                  "western", 
                                  time_af)
```


## Distribution of tweet sentiment by region (Jan 1 2022-Jan 6 2023)

```{r}
barplot_state_sentiment_by_region(state_sent_props, 
                                  northeast, 
                                  "northeastern", 
                                  time_comp)
barplot_state_sentiment_by_region(state_sent_props, 
                                  midwest, 
                                  "midwestern", 
                                  time_comp)
barplot_state_sentiment_by_region(state_sent_props, 
                                  south, 
                                  "southern", 
                                  time_comp)
barplot_state_sentiment_by_region(state_sent_props, 
                                  west, 
                                  "western", 
                                  time_comp)
```



```{r}
library(table1)
no_na_st <- dat[!is.na(dat$state),]
dim(no_na_st)
dim(dat)
table1(~  + factor(state) | factor(sentiment) + factor(RoeWadeOverturn), data = no_na_st,
       caption = "Distribution of sentiment by state")

table1(~  + factor(state) | factor(sentiment) + factor(RoeWadeOverturn), overall = FALSE, data = no_na_st, caption = "Distribution of sentiment by state before and after the overturn")
```


